apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-gnba
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-empty-private-gnba
    app.kubernetes.io/part-of: mc-golang-without
  name: devfile-sample-go-basic-dockerfile-empty-private-gnba
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-gnba
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-gnba
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zttl-tenant/mc-golang-without/devfile-sample-go-basic-dockerfile-empty-private-gnba@sha256:8af1521388567a1216396930205c60f7064cc74675ded59391baec41998db5a3
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
